# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYaHMYKrbe_lXZHvLYGWpcBPGhvSPbP9
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist

# Load dataset
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# Preprocess
X_train = X_train.reshape(-1, 784) / 255.0
X_test = X_test.reshape(-1, 784) / 255.0

# One-hot encoding
def one_hot(y):
    out = np.zeros((y.size, 10))
    out[np.arange(y.size), y] = 1
    return out

y_train_oh = one_hot(y_train)
y_test_oh = one_hot(y_test)

# Initialize parameters
input_size = 784
hidden_size = 128
output_size = 10
lr = 0.1
epochs = 25

W1 = np.random.randn(input_size, hidden_size) * 0.01
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size) * 0.01
b2 = np.zeros((1, output_size))

def relu(z):
    return np.maximum(0, z)

def relu_deriv(z):
    return (z > 0).astype(float)

def softmax(z):
    exp = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp / np.sum(exp, axis=1, keepdims=True)

def cross_entropy(y, y_hat):
    return -np.mean(np.sum(y * np.log(y_hat + 1e-9), axis=1))

losses = []

for epoch in range(epochs):

    # Forward
    z1 = X_train @ W1 + b1
    a1 = relu(z1)
    z2 = a1 @ W2 + b2
    y_hat = softmax(z2)

    # Loss
    loss = cross_entropy(y_train_oh, y_hat)
    losses.append(loss)

    # Backprop
    m = X_train.shape[0]
    dz2 = y_hat - y_train_oh
    dW2 = a1.T @ dz2 / m
    db2 = np.sum(dz2, axis=0, keepdims=True) / m

    dz1 = (dz2 @ W2.T) * relu_deriv(z1)
    dW1 = X_train.T @ dz1 / m
    db1 = np.sum(dz1, axis=0, keepdims=True) / m

    # Update
    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2

    print(f"Epoch {epoch+1}, Loss: {loss:.4f}")

# Test accuracy
z1 = X_test @ W1 + b1
a1 = relu(z1)
z2 = a1 @ W2 + b2
y_hat = softmax(z2)

preds = np.argmax(y_hat, axis=1)
accuracy = np.mean(preds == y_test)
print("Test Accuracy:", accuracy)

plt.plot(losses)
plt.title("MLP Loss")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist

# -----------------------
# LOAD DATA
# -----------------------
(X_train, _), _ = fashion_mnist.load_data()

# Preprocess
X_train = X_train.reshape(-1, 784) / 255.0

# Use smaller subset for fast training
X_train = X_train[:10000]

# -----------------------
# HYPERPARAMETERS
# -----------------------
input_size = 784
latent_size = 32
lr = 0.1
epochs = 15
lambda_reg = 0.001   # Sparsity strength

# -----------------------
# INITIALIZE WEIGHTS
# -----------------------
W1 = np.random.randn(input_size, latent_size) * 0.01
b1 = np.zeros((1, latent_size))

W2 = np.random.randn(latent_size, input_size) * 0.01
b2 = np.zeros((1, input_size))

# -----------------------
# ACTIVATION
# -----------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# -----------------------
# TRAINING LOOP
# -----------------------
losses = []

for epoch in range(epochs):

    # Forward pass
    z1 = X_train @ W1 + b1
    a1 = sigmoid(z1)          # Latent representation

    z2 = a1 @ W2 + b2
    output = sigmoid(z2)      # Reconstruction

    # Sparse Loss (MSE + L1 penalty on latent layer)
    mse_loss = np.mean((X_train - output) ** 2)
    sparse_loss = lambda_reg * np.mean(np.abs(a1))
    loss = mse_loss + sparse_loss

    losses.append(loss)

    # Backpropagation
    m = X_train.shape[0]

    dz2 = (output - X_train) * output * (1 - output)
    dW2 = a1.T @ dz2 / m
    db2 = np.sum(dz2, axis=0, keepdims=True) / m

    dz1 = (dz2 @ W2.T) * a1 * (1 - a1)
    dW1 = X_train.T @ dz1 / m
    db1 = np.sum(dz1, axis=0, keepdims=True) / m

    # Update
    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2

    print(f"Epoch {epoch+1}, Loss: {loss:.6f}")

# -----------------------
# PLOT LOSS CURVE
# -----------------------
plt.plot(losses)
plt.title("Sparse Autoencoder Reconstruction Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

# -----------------------
# OUTLIER DETECTION
# -----------------------
recon_error = np.mean((X_train - output) ** 2, axis=1)

threshold = np.mean(recon_error) + 2 * np.std(recon_error)

outliers = np.where(recon_error > threshold)[0]

print("Outliers detected:", len(outliers))

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist

# Load dataset
(X_train, _), _ = fashion_mnist.load_data()
X_train = X_train.reshape(-1, 784) / 255.0

# Use smaller subset for speed
X_train = X_train[:10000]

visible = 784
hidden = 100
lr = 0.01
epochs = 10

# Initialize weights
W = np.random.randn(visible, hidden) * 0.01

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

errors = []

for epoch in range(epochs):

    # Positive phase
    v0 = X_train
    h0 = sigmoid(v0 @ W)

    # Negative phase (reconstruction)
    v1 = sigmoid(h0 @ W.T)
    h1 = sigmoid(v1 @ W)

    # Contrastive Divergence update
    W += lr * (v0.T @ h0 - v1.T @ h1) / X_train.shape[0]

    error = np.mean((v0 - v1) ** 2)
    errors.append(error)

    print(f"Epoch {epoch+1}, Reconstruction Error: {error:.6f}")

plt.plot(errors)
plt.title("RBM Reconstruction Error")
plt.xlabel("Epoch")
plt.ylabel("Error")
plt.show()